#!/usr/bin/env python3
"""Kashyyyk patrol routes: SOE's patrol_spawner rows and their patrol_waypoint rows, transcribed into
bin/scripts/screenplays/kashyyyk/kashyyyk_patrol_paths.lua in merged-snapshot world coordinates.

Usage:  build_patrol_paths.py --dsrc <path to sys.server/compiled/game/datatables> [--scripts <path to bin/scripts>]

Reads the three surface buildout tabs (kashyyyk_main, kashyyyk_hunting, kashyyyk_dead_forest), pairs every
patrol_spawner's strPatrolPointNames with the patrol_waypoint rows of the same tab (pointName), applies the proved
buildout-to-world offsets, and writes one Lua entry per route with the repo mobiles its type table's lair carries.
The SOE data itself is never committed; only this tool and its Lua output are.
"""
import argparse, json, os, re, sys

ZONES = {  # tab-zone -> (dx, dz, Core3 zone, tab file); world = buildout + (dx, dz), proved per sub-zone
    'kashyyyk_main': (-4096.0, -4096.0, 'kashyyyk', 'kashyyyk_main.tab'),
    'kashyyyk_hunting': (-2048.0, -5048.0, 'kashyyyk', 'kashyyyk_hunting.tab'),
    'kashyyyk_dead_forest': (-3548.0, -548.0, 'kashyyyk', 'kashyyyk_dead_forest.tab'),
    # the dungeon zones (option-(a) TRE order; offsets measured in the spawn rounds)
    'kashyyyk_north_dungeons': (-3840.0, 2816.0, 'kashyyyk_north_dungeons', 'slaver.tab'),
    'kashyyyk_rryatt_trail_lvl_1_and_2': (-3908.0, 3365.0, 'kashyyyk_rryatt_trail', 'kashyyyk_rryatt_trail_lvl_1_and_2.tab'),
}


def objvars(s):
    d = {}
    parts = s.split('|')
    i = 0
    while i + 2 < len(parts):
        if parts[i] == '$':
            break
        d[parts[i]] = parts[i + 2]
        i += 3
    return d


def read_zone(dsrc, zone):
    dx, dz, core3_zone, tab = ZONES[zone]
    zone_dir = zone if not zone.startswith('kashyyyk_rryatt_trail') else 'kashyyyk_rryatt_trail'
    path = os.path.join(dsrc, 'buildout', zone_dir, tab)
    lines = open(path, encoding='utf-8', errors='replace').read().split('\n')
    ci = {n: i for i, n in enumerate(lines[0].split('\t'))}
    waypoints, spawners = {}, []
    for row, line in enumerate(lines[2:], start=3):
        c = line.split('\t')
        if len(c) < len(ci):  # 13-column and 11-column tabs alike
            continue
        tpl = c[ci['server_template_crc']]
        px, py, pz = float(c[ci['px']]), float(c[ci['py']]), float(c[ci['pz']])
        ov = objvars(c[ci['objvars']])
        if tpl.endswith('patrol_waypoint.iff'):
            waypoints[ov.get('pointName', '')] = {'row': row, 'wx': round(px + dx, 2), 'height': round(py, 2), 'wz': round(pz + dz, 2)}
        elif tpl.endswith('patrol_spawner.iff'):
            spawners.append({
                'row': row, 'name': ov.get('strName', ''), 'strSpawns': ov['strSpawns'],
                'count': int(ov.get('intSpawnCount', '1')), 'minTime': float(ov.get('fltMinSpawnTime', '0')),
                'maxTime': float(ov.get('fltMaxSpawnTime', '0')), 'pathType': ov.get('patrolPathType', 'cycle'),
                'points': [p for p in ov.get('strPatrolPointNames', '').split(':') if p],
            })
    for s in spawners:
        s['path'] = [waypoints[p] for p in s['points'] if p in waypoints]
        s['missing'] = len(s['points']) - len(s['path'])
    return spawners, len(waypoints)


def lair_mobiles(scripts, str_spawns, extra_lair_dirs=()):
    stem = 'kashyyyk_' + str_spawns.split('/')[-1]
    dirs = [os.path.join(scripts, 'mobile', 'lair', 'creature_dynamic')] + list(extra_lair_dirs)
    for d in dirs:  # the dungeon-zone lairs live on the dungeons branch until the branches merge
        path = os.path.join(d, stem + '.lua')
        if os.path.exists(path):
            return re.findall(r'\{"([A-Za-z0-9_]+)",\s*\d+\}', open(path, encoding='utf-8').read())
    return None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--dsrc', required=True)
    ap.add_argument('--scripts', default=os.path.join(os.path.dirname(__file__), '..', '..', 'bin', 'scripts'))
    ap.add_argument('--lairs', action='append', default=[], help='extra lair directories to resolve type tables against')
    a = ap.parse_args()
    out = [
        '-- SOURCED -- SOE patrol spawners and their waypoint rows, from the three Kashyyyk surface buildout tabs',
        '--   datatables/buildout/kashyyyk_main/kashyyyk_main.tab (world = buildout - 4096 on x and z)',
        '--   datatables/buildout/kashyyyk_hunting/kashyyyk_hunting.tab (world = (x - 2048, z - 5048))',
        '--   datatables/buildout/kashyyyk_dead_forest/kashyyyk_dead_forest.tab (world = (x - 3548, z - 548))',
        '--   datatables/buildout/kashyyyk_north_dungeons/slaver.tab (zone kashyyyk_north_dungeons; world = (x - 3840, z + 2816))',
        '--   datatables/buildout/kashyyyk_rryatt_trail/kashyyyk_rryatt_trail_lvl_1_and_2.tab (zone kashyyyk_rryatt_trail; world = (x - 3908, z + 3365))',
        '-- Generated by tools/kashyyyk/build_patrol_paths.py (ruling 2026-09-04: "ensure kashyyyk is done in full"). Do not hand-edit.',
        '-- Each entry: name (SOE strName), zone tab, spawnZone (the Core3 zone the route is in), buildout row, the type table',
        '-- (strSpawns), the repo mobiles that lair carries',
        '-- (from mobile/lair/creature_dynamic/kashyyyk_<type>.lua), count (intSpawnCount), respawn min/max seconds, path type',
        '-- (cycle = loop, oscillate = there and back), and the waypoints in order as {x, z (height), y} world coordinates.',
        '-- Two dead-forest routes reference waypoint names SOE never placed (forest_warchief 12 of 28, Cyrans 9 of 28); the',
        '-- placed points keep their order and the gaps are simply skipped.',
        'KashyyykPatrolPaths = {',
    ]
    routes = 0
    for zone in ZONES:
        spawners, nwp = read_zone(a.dsrc, zone)
        print(zone, 'spawners', len(spawners), 'waypoints', nwp, file=sys.stderr)
        for s in spawners:
            mobs = lair_mobiles(a.scripts, s['strSpawns'], a.lairs)
            if not mobs:
                out.append(f'\t-- OPEN: {s["name"]} ({zone} row {s["row"]}) type {s["strSpawns"]} has no lair (no repo template); {len(s["path"])} points, not spawned')
                continue
            routes += 1
            out.append('\t{')
            out.append(f'\t\tname = "{s["name"]}", zone = "{zone}", spawnZone = "{ZONES[zone][2]}", row = {s["row"]}, typeTable = "{s["strSpawns"]}",')
            out.append('\t\tmobiles = {' + ', '.join(f'"{m}"' for m in mobs) + '},')
            out.append(f'\t\tcount = {s["count"]}, respawnMin = {int(s["minTime"])}, respawnMax = {int(s["maxTime"])}, pathType = "{s["pathType"]}",')
            out.append('\t\tpoints = {')
            for p in s['path']:
                out.append(f'\t\t\t{{{p["wx"]}, {p["height"]:.2f}, {p["wz"]}}},')
            out.append('\t\t},')
            out.append('\t},')
    out.append('}')
    dest = os.path.join(a.scripts, 'screenplays', 'kashyyyk', 'kashyyyk_patrol_paths.lua')
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    open(dest, 'w', encoding='utf-8', newline='\r\n').write('\n'.join(out) + '\n')
    print('routes written', routes, '->', dest, file=sys.stderr)


if __name__ == '__main__':
    main()
